apiVersion: v1
kind: PersistentVolume
metadata:
    name: settool-pv
    namespace: settool
    labels:
        app: settool
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    persistentVolumeReclaimPolicy: Delete
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data/settool'
