apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: settool-mediafiles-pvc
  namespace: settool
  labels:
    app: settool
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
