image: python:3.8-buster

stages:
  - test
  - linting

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

all_tests:
  stage: test
  before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip3 install -U -r requirements.txt
    - pip3 install -U -r cli/requirements_dev.txt
  script:
    - python3 manage.py test

bandit:
  stage: linting
  before_script:
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip3 install -U bandit
  script:
    - bandit -r .

mypy:
  stage: linting
  before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip3 install -U -r requirements.txt
    - pip3 install -U -r cli/requirements_dev.txt
  script:
    - mypy --ignore-missing-imports .
  allow_failure: true

pylint:
  stage: linting
  before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip install -U -r requirements.txt
    - pip install -U pylint pylint-django
  script:
    - pylint ./**/*.py
