image: python:3.7-buster

before_script:
  - apt-get update

pre-commit:
    variables:
        PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .cache/pip
            - .cache/pre-commit
            - venv
    script:
        - apt-get -qq install -y xmlsec1 libldap2-dev libsasl2-dev gettext
        - python -m venv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install pre-commit -r requirements.txt -r requirements_dev.txt
        - pre-commit run --show-diff-on-failure --color=always --all-files
