image: python:3.8-buster

stages:
  - test
  - linting

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
    - apt-get update && apt-get install -y build-essential libldap2-dev libsasl2-dev
    - pip3 install virtualenv
    - virtualenv -q .venv
    - source .venv/bin/activate
    - pip3 install -U -r requirements.txt
    - pip3 install -U -r requirements_dev.txt

run_pytests:
  stage: test
  script:
    - python3 manage.py test

bandit:
  stage: linting
  script:
    - bandit -r .
  allow_failure: true

mypy:
  stage: linting
  script:
    - mypy --ignore-missing-imports .
  allow_failure: true

pylint:
  stage: linting
  script:
    - pylint ./**/*.py
  allow_failure: true
