repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-ast
          - id: check-toml
          - id: check-yaml
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-docstring-first
          - id: debug-statements
          - id: name-tests-test
            args: [--django]
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
    - repo: https://github.com/PyCQA/isort
      rev: 5.6.4
      hooks:
          - id: isort
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.0.1
      hooks:
          - id: add-trailing-comma
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.7.0
      hooks:
          - id: python-use-type-annotations
