[tool.black]
line-length = 100

[tool.isort]
line_length = 100
force_single_line = true
lexicographical = true
order_by_type = false

[tool.coverage.run]
source = ["."]

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = true
omit = [
    "venv/*",
    "node_modules",
    "manage.py",
]
