name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: python:3.7-buster
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_dev.txt
        sudo apt-get update
        sudo apt-get -qq install -y gettext texlive-base texlive-lang-german texlive-fonts-recommended texlive-latex-extra latexmk

    - name: Run Tests
      run: |
        python manage.py test
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        extra_args: --show-diff-on-failure --color=always --all-files
