name: Main CI

on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4

        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2.2.2
              with:
                  python-version: 3.7
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt -r requirements_dev.txt
                  sudo apt-get update
                  sudo apt-get -qq install -y gettext texlive-base texlive-lang-german texlive-fonts-recommended texlive-latex-extra latexmk
            - name: Run Tests
              run: |
                  python manage.py test

    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2.2.2
              with:
                  python-version: 3.7
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt -r requirements_dev.txt
                  sudo apt-get update
                  sudo apt-get -qq install -y npm
            - name: Install npm packages
              run: npm install
            - name: Linelint
              uses: actions/linelint@master
              id: linelint1
            - name: Commit npm packages
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Automated Change: updated npm requirements'
            - name: install update pre-commit
              run: pre-commit autoupdate
            - name: Linelint
              uses: actions/linelint@master
              id: linelint2
            - name: Commit pre-commit file if changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Automated Change: updated npm requirements'
